Evaluate performance of covariates on TP53
cognoma/machine-learning pull request #47
Opened 2016-09-15 15:12 UTC by dhimmel

Creates an explore directory and README for this type of exploratory notebook.

See how well covariates (non-expression features) predict TP53 mutation.

Related to https://github.com/cognoma/machine-learning/issues/8: General mutation-load does provide some ability to predict mutation status of TP53.

Partially addresses https://github.com/cognoma/machine-learning/issues/21: Covariates are extracted from `samples.tsv`.

2016-09-15 15:45 UTC, cgreene commented
> Related to #8: General mutation-load does provide some ability to predict mutation status of TP53.

This isn't too surprising given TP53's role in controlling cell cycle checkpoints. Is this only true for genes in cell cycle checkpoint or DNA repair pathways, or is it also true for genes in proliferation pathways?

2016-09-19 16:32 UTC, dhimmel commented
> Is this only true for genes in cell cycle checkpoint or DNA repair pathways, or is it also true for genes in proliferation pathways?

@cgreene, I updated the notebook to evaluate performance of covariate-only classifiers for the 8 interesting mutations we've [previously considered](https://github.com/cognoma/cancer-data/pull/22#issuecomment-245294155). Here is performance of the models with all covariates included:

![covariate-performance](https://cloud.githubusercontent.com/assets/1117703/18639994/1ebc17e8-7e64-11e6-8955-df34631c7266.png)

So actually, _TP53_ is among the hardest to predict using only covariates. _VHL_ which is highly disease-specific achieves a near-perfect AUROC. Therefore, without the disease or organ covariate, expression classifiers of _VHL_ are likely just classifying kidney clear cell carcinoma / kidney tissue.

See [this dataframe](https://github.com/dhimmel/machine-learning/blob/50aa17482dd1f9ebfae7d98fcf98a0209eb86487/explore/confounding/auroc.tsv) to get a general idea of covariate importance. Mutation load and disease type both seem important.

2016-09-19 17:57 UTC, cgreene commented
@dhimmel : Interesting! I can imagine that gene expression would clearly capture disease/organ, so if one usually had a mutation in a single gene that was relatively specific (e.g. VHL) I could imagine that creating a strong signal.

2016-09-19 20:20 UTC, gwaygenomics commented on explore/confounding/confounding.py
> +
looks like you need to `nbconvert` this again

2016-09-19 20:20 UTC, gwaygenomics commented on explore/confounding/confounding.py
> +
I'll take a look again once it's easier to read

2016-09-19 20:21 UTC, gwaybio requested changes
looks like nbconvert `confounding.ipynb` has to be rerun

2016-09-21 16:41 UTC, dhimmel commented on explore/confounding/confounding.py
> +
Good catch. should be fixed now.

2016-09-21 20:04 UTC, gwaygenomics commented on explore/confounding/confounding.py
> +    '7157': 'TP53', # tumor protein p53
pep8 says inline comments should be separated by [two spaces](https://www.python.org/dev/peps/pep-0008/#inline-comments)

2016-09-21 20:07 UTC, gwaygenomics commented on explore/confounding/confounding.py
> +    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
what does `series` look like?

2016-09-21 20:11 UTC, gwaybio requested changes
Interesting and informative analysis. My comments are generally cosmetic, but it would be nice to get some additional documentation on some of the functions!

2016-09-21 20:11 UTC, gwaybio commented on explore/README.md
> +This directory is home is exploratory analyses that help answer questions about how we should do machine learning. For algorithm implementations see the [`algorithms`](../algorithms) directory. For o
"This directory is home **to** exploratory analyses"?

2016-09-21 20:11 UTC, gwaybio commented on explore/confounding/confounding.py
> +# # Create a logistic regression model to several mutations from covariates
"Create a logistic regression model to **predict** several mutations from covariates"?

2016-09-21 23:41 UTC, gwaybio approved these changes

2016-09-22 13:28 UTC, merged