Cognoma feature selection using PCA (2000 features)
cognoma/machine-learning pull request #48
Opened 2016-09-16 00:05 UTC by mans2singh

Hey Folks:

First cut of feature selection using PCA (2000 features).   Let me know your comments/recommendations.

Thanks

2016-09-16 18:26 UTC, dhimmel commented on algorithms/scripts/SGDClassifier-PCA-mans2singh.py
> +feature_select = PCA(n_components=n_feature_kept)
Should this be renamed to `feature_transform` because we're doing more than just selection?

2016-09-16 18:27 UTC, dhimmel requested changes
Looks good to me besides my single comment

2016-09-16 23:24 UTC, mans2singh commented
@dhimmel - Thanks for your comments.  I've updated the variable to feature_transform.  Let me know if you have any other recommendation. 

Thanks

2016-09-17 18:15 UTC, dhimmel commented
@mans2singh, nice work. Performance looks good: testing AUROC = 93.1% and training AUROC = 95.2%. I don't think we can directly compare it to not using PCA, since I didn't see another notebook that used `n_feature_kept = 2000`.

I'm going to merge now. However, if you'd like to keep working on this, you can submit another pull request with additional modifications. Future directions could be

1. comparing PCA to MAD feature selection or no feature selection
2. plotting cumulative explained variance versus number of components

2016-09-17 18:15 UTC, dhimmel approved these changes

2016-09-17 18:17 UTC, merged

2016-09-17 22:05 UTC, mans2singh commented
Thanks @dhimmel